services:
  content-server:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: content_server

    restart: unless-stopped

    ports:
      - "4000:4000"

    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      CONTENT_ROOT: /data

    volumes:
      - /home/lwojas/docker/_apps/content_server_data:/data
